/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.gd.trans.example.demo.thrift;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.12.0)", date = "2020-10-16")
public class UnFreezeModel implements org.apache.thrift.TBase<UnFreezeModel, UnFreezeModel._Fields>, java.io.Serializable, Cloneable, Comparable<UnFreezeModel> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("UnFreezeModel");

  private static final org.apache.thrift.protocol.TField BIZ_NO_FIELD_DESC = new org.apache.thrift.protocol.TField("bizNo", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField BALANCE_FIELD_DESC = new org.apache.thrift.protocol.TField("balance", org.apache.thrift.protocol.TType.STRING, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new UnFreezeModelStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new UnFreezeModelTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable String bizNo; // required
  public @org.apache.thrift.annotation.Nullable String balance; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    BIZ_NO((short)1, "bizNo"),
    BALANCE((short)2, "balance");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // BIZ_NO
          return BIZ_NO;
        case 2: // BALANCE
          return BALANCE;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.BIZ_NO, new org.apache.thrift.meta_data.FieldMetaData("bizNo", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.BALANCE, new org.apache.thrift.meta_data.FieldMetaData("balance", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(UnFreezeModel.class, metaDataMap);
  }

  public UnFreezeModel() {
  }

  public UnFreezeModel(
    String bizNo,
    String balance)
  {
    this();
    this.bizNo = bizNo;
    this.balance = balance;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public UnFreezeModel(UnFreezeModel other) {
    if (other.isSetBizNo()) {
      this.bizNo = other.bizNo;
    }
    if (other.isSetBalance()) {
      this.balance = other.balance;
    }
  }

  public UnFreezeModel deepCopy() {
    return new UnFreezeModel(this);
  }

  @Override
  public void clear() {
    this.bizNo = null;
    this.balance = null;
  }

  @org.apache.thrift.annotation.Nullable
  public String getBizNo() {
    return this.bizNo;
  }

  public UnFreezeModel setBizNo(@org.apache.thrift.annotation.Nullable String bizNo) {
    this.bizNo = bizNo;
    return this;
  }

  public void unsetBizNo() {
    this.bizNo = null;
  }

  /** Returns true if field bizNo is set (has been assigned a value) and false otherwise */
  public boolean isSetBizNo() {
    return this.bizNo != null;
  }

  public void setBizNoIsSet(boolean value) {
    if (!value) {
      this.bizNo = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public String getBalance() {
    return this.balance;
  }

  public UnFreezeModel setBalance(@org.apache.thrift.annotation.Nullable String balance) {
    this.balance = balance;
    return this;
  }

  public void unsetBalance() {
    this.balance = null;
  }

  /** Returns true if field balance is set (has been assigned a value) and false otherwise */
  public boolean isSetBalance() {
    return this.balance != null;
  }

  public void setBalanceIsSet(boolean value) {
    if (!value) {
      this.balance = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case BIZ_NO:
      if (value == null) {
        unsetBizNo();
      } else {
        setBizNo((String)value);
      }
      break;

    case BALANCE:
      if (value == null) {
        unsetBalance();
      } else {
        setBalance((String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case BIZ_NO:
      return getBizNo();

    case BALANCE:
      return getBalance();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case BIZ_NO:
      return isSetBizNo();
    case BALANCE:
      return isSetBalance();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof UnFreezeModel)
      return this.equals((UnFreezeModel)that);
    return false;
  }

  public boolean equals(UnFreezeModel that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_bizNo = true && this.isSetBizNo();
    boolean that_present_bizNo = true && that.isSetBizNo();
    if (this_present_bizNo || that_present_bizNo) {
      if (!(this_present_bizNo && that_present_bizNo))
        return false;
      if (!this.bizNo.equals(that.bizNo))
        return false;
    }

    boolean this_present_balance = true && this.isSetBalance();
    boolean that_present_balance = true && that.isSetBalance();
    if (this_present_balance || that_present_balance) {
      if (!(this_present_balance && that_present_balance))
        return false;
      if (!this.balance.equals(that.balance))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetBizNo()) ? 131071 : 524287);
    if (isSetBizNo())
      hashCode = hashCode * 8191 + bizNo.hashCode();

    hashCode = hashCode * 8191 + ((isSetBalance()) ? 131071 : 524287);
    if (isSetBalance())
      hashCode = hashCode * 8191 + balance.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(UnFreezeModel other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetBizNo()).compareTo(other.isSetBizNo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBizNo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.bizNo, other.bizNo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetBalance()).compareTo(other.isSetBalance());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBalance()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.balance, other.balance);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("UnFreezeModel(");
    boolean first = true;

    sb.append("bizNo:");
    if (this.bizNo == null) {
      sb.append("null");
    } else {
      sb.append(this.bizNo);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("balance:");
    if (this.balance == null) {
      sb.append("null");
    } else {
      sb.append(this.balance);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (bizNo == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'bizNo' was not present! Struct: " + toString());
    }
    if (balance == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'balance' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class UnFreezeModelStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UnFreezeModelStandardScheme getScheme() {
      return new UnFreezeModelStandardScheme();
    }
  }

  private static class UnFreezeModelStandardScheme extends org.apache.thrift.scheme.StandardScheme<UnFreezeModel> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, UnFreezeModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // BIZ_NO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.bizNo = iprot.readString();
              struct.setBizNoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // BALANCE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.balance = iprot.readString();
              struct.setBalanceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, UnFreezeModel struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.bizNo != null) {
        oprot.writeFieldBegin(BIZ_NO_FIELD_DESC);
        oprot.writeString(struct.bizNo);
        oprot.writeFieldEnd();
      }
      if (struct.balance != null) {
        oprot.writeFieldBegin(BALANCE_FIELD_DESC);
        oprot.writeString(struct.balance);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class UnFreezeModelTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public UnFreezeModelTupleScheme getScheme() {
      return new UnFreezeModelTupleScheme();
    }
  }

  private static class UnFreezeModelTupleScheme extends org.apache.thrift.scheme.TupleScheme<UnFreezeModel> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, UnFreezeModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.bizNo);
      oprot.writeString(struct.balance);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, UnFreezeModel struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.bizNo = iprot.readString();
      struct.setBizNoIsSet(true);
      struct.balance = iprot.readString();
      struct.setBalanceIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

